### PR TITLE
Fix issue when mentioning a profile with an emoji

### LINKED ISSUE #327: BUG: Cannot publish mention with emoji
Steps to reproduce:
1. Try to reply to a post that mentions a user with an emoji in their name.
Expected: The reply posts successfully.
Actual: an error is shown.

Rabble observed one instance of this replying to message `%9762qpy0pwYbXAjdXfqp9JVLAm4C8Sw9OknYvvQqnd8=.sha256` I think the name with emoji was "andrestaltz📱". [Bugsnag link](https://app.bugsnag.com/verse/planetary/errors/61f4a2633d48b0000913ae37?event_id=61f4a263008d383d28d80000&i=sk&m=nw

### PR DESCRIPTION
**Pull request by martindsq**
Closes #327
Converting a Mention to a NSAttributedString wasn't done properly. Check accepted answer [here](https://stackoverflow.com/questions/56470728/swift-nsattributedstring-emojis).

### CODE REVIEW

File: UnitTests/GoBotIntegrationTests.swift [hunk 1]
```diff
@@ -184,6 +184,73 @@ class GoBotIntegrationTests: XCTestCase {
...
+
+        // Act
+        let ref = try await sut.publish(content: testPost)
+
+        // Assert
+        XCTAssertEqual(appConfig.numberOfPublishedMessages, 1)
+        XCTAssertNotNil(ref)
+    }
+
+    /// Verifies that the GoBOt can publish a message with a mention whose name has an emoji
```
Comment (mplorentz) [inline UnitTests/GoBotIntegrationTests.swift:228]:
```suggestion
    /// Verifies that the GoBot can publish a message with a mention whose name has an emoji
```

**Review by mplorentz — APPROVED** [review]
Lovely tests ❤️ 

I saw one typo, but this looks great!
